// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface CartItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CartItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 productId = 2;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>string Time = 4;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string Time = 4;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string Date = 5;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string Date = 5;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
