// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface CartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Cart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  java.util.List<proto.example.Schema.CartItem> 
      getCartItemsList();
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  proto.example.Schema.CartItem getCartItems(int index);
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.CartItemOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .CartItem cartItems = 1;</code>
   */
  proto.example.Schema.CartItemOrBuilder getCartItemsOrBuilder(
      int index);
}
