// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

/**
 * Protobuf type {@code Coupons}
 */
public final class Coupons extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Coupons)
    CouponsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Coupons.newBuilder() to construct.
  private Coupons(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Coupons() {
    coupons_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Coupons();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Coupons(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              coupons_ = new java.util.ArrayList<proto.example.Schema.Coupon>();
              mutable_bitField0_ |= 0x00000001;
            }
            coupons_.add(
                input.readMessage(proto.example.Schema.Coupon.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        coupons_ = java.util.Collections.unmodifiableList(coupons_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.example.Schema.SchemaProtos.internal_static_Coupons_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.example.Schema.SchemaProtos.internal_static_Coupons_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.example.Schema.Coupons.class, proto.example.Schema.Coupons.Builder.class);
  }

  public static final int COUPONS_FIELD_NUMBER = 1;
  private java.util.List<proto.example.Schema.Coupon> coupons_;
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.example.Schema.Coupon> getCouponsList() {
    return coupons_;
  }
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.example.Schema.CouponOrBuilder> 
      getCouponsOrBuilderList() {
    return coupons_;
  }
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  @java.lang.Override
  public int getCouponsCount() {
    return coupons_.size();
  }
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  @java.lang.Override
  public proto.example.Schema.Coupon getCoupons(int index) {
    return coupons_.get(index);
  }
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  @java.lang.Override
  public proto.example.Schema.CouponOrBuilder getCouponsOrBuilder(
      int index) {
    return coupons_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < coupons_.size(); i++) {
      output.writeMessage(1, coupons_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < coupons_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, coupons_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.example.Schema.Coupons)) {
      return super.equals(obj);
    }
    proto.example.Schema.Coupons other = (proto.example.Schema.Coupons) obj;

    if (!getCouponsList()
        .equals(other.getCouponsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCouponsCount() > 0) {
      hash = (37 * hash) + COUPONS_FIELD_NUMBER;
      hash = (53 * hash) + getCouponsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.example.Schema.Coupons parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.Schema.Coupons parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.Schema.Coupons parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.Schema.Coupons parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.Schema.Coupons parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.Schema.Coupons parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.Schema.Coupons parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.example.Schema.Coupons parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.example.Schema.Coupons parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.example.Schema.Coupons parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.example.Schema.Coupons parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.example.Schema.Coupons parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.example.Schema.Coupons prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Coupons}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Coupons)
      proto.example.Schema.CouponsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.example.Schema.SchemaProtos.internal_static_Coupons_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.example.Schema.SchemaProtos.internal_static_Coupons_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.example.Schema.Coupons.class, proto.example.Schema.Coupons.Builder.class);
    }

    // Construct using proto.example.Schema.Coupons.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCouponsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (couponsBuilder_ == null) {
        coupons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        couponsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.example.Schema.SchemaProtos.internal_static_Coupons_descriptor;
    }

    @java.lang.Override
    public proto.example.Schema.Coupons getDefaultInstanceForType() {
      return proto.example.Schema.Coupons.getDefaultInstance();
    }

    @java.lang.Override
    public proto.example.Schema.Coupons build() {
      proto.example.Schema.Coupons result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.example.Schema.Coupons buildPartial() {
      proto.example.Schema.Coupons result = new proto.example.Schema.Coupons(this);
      int from_bitField0_ = bitField0_;
      if (couponsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          coupons_ = java.util.Collections.unmodifiableList(coupons_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.coupons_ = coupons_;
      } else {
        result.coupons_ = couponsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.example.Schema.Coupons) {
        return mergeFrom((proto.example.Schema.Coupons)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.example.Schema.Coupons other) {
      if (other == proto.example.Schema.Coupons.getDefaultInstance()) return this;
      if (couponsBuilder_ == null) {
        if (!other.coupons_.isEmpty()) {
          if (coupons_.isEmpty()) {
            coupons_ = other.coupons_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCouponsIsMutable();
            coupons_.addAll(other.coupons_);
          }
          onChanged();
        }
      } else {
        if (!other.coupons_.isEmpty()) {
          if (couponsBuilder_.isEmpty()) {
            couponsBuilder_.dispose();
            couponsBuilder_ = null;
            coupons_ = other.coupons_;
            bitField0_ = (bitField0_ & ~0x00000001);
            couponsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCouponsFieldBuilder() : null;
          } else {
            couponsBuilder_.addAllMessages(other.coupons_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.example.Schema.Coupons parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.example.Schema.Coupons) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<proto.example.Schema.Coupon> coupons_ =
      java.util.Collections.emptyList();
    private void ensureCouponsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        coupons_ = new java.util.ArrayList<proto.example.Schema.Coupon>(coupons_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.example.Schema.Coupon, proto.example.Schema.Coupon.Builder, proto.example.Schema.CouponOrBuilder> couponsBuilder_;

    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public java.util.List<proto.example.Schema.Coupon> getCouponsList() {
      if (couponsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(coupons_);
      } else {
        return couponsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public int getCouponsCount() {
      if (couponsBuilder_ == null) {
        return coupons_.size();
      } else {
        return couponsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public proto.example.Schema.Coupon getCoupons(int index) {
      if (couponsBuilder_ == null) {
        return coupons_.get(index);
      } else {
        return couponsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder setCoupons(
        int index, proto.example.Schema.Coupon value) {
      if (couponsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCouponsIsMutable();
        coupons_.set(index, value);
        onChanged();
      } else {
        couponsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder setCoupons(
        int index, proto.example.Schema.Coupon.Builder builderForValue) {
      if (couponsBuilder_ == null) {
        ensureCouponsIsMutable();
        coupons_.set(index, builderForValue.build());
        onChanged();
      } else {
        couponsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder addCoupons(proto.example.Schema.Coupon value) {
      if (couponsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCouponsIsMutable();
        coupons_.add(value);
        onChanged();
      } else {
        couponsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder addCoupons(
        int index, proto.example.Schema.Coupon value) {
      if (couponsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCouponsIsMutable();
        coupons_.add(index, value);
        onChanged();
      } else {
        couponsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder addCoupons(
        proto.example.Schema.Coupon.Builder builderForValue) {
      if (couponsBuilder_ == null) {
        ensureCouponsIsMutable();
        coupons_.add(builderForValue.build());
        onChanged();
      } else {
        couponsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder addCoupons(
        int index, proto.example.Schema.Coupon.Builder builderForValue) {
      if (couponsBuilder_ == null) {
        ensureCouponsIsMutable();
        coupons_.add(index, builderForValue.build());
        onChanged();
      } else {
        couponsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder addAllCoupons(
        java.lang.Iterable<? extends proto.example.Schema.Coupon> values) {
      if (couponsBuilder_ == null) {
        ensureCouponsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, coupons_);
        onChanged();
      } else {
        couponsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder clearCoupons() {
      if (couponsBuilder_ == null) {
        coupons_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        couponsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public Builder removeCoupons(int index) {
      if (couponsBuilder_ == null) {
        ensureCouponsIsMutable();
        coupons_.remove(index);
        onChanged();
      } else {
        couponsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public proto.example.Schema.Coupon.Builder getCouponsBuilder(
        int index) {
      return getCouponsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public proto.example.Schema.CouponOrBuilder getCouponsOrBuilder(
        int index) {
      if (couponsBuilder_ == null) {
        return coupons_.get(index);  } else {
        return couponsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public java.util.List<? extends proto.example.Schema.CouponOrBuilder> 
         getCouponsOrBuilderList() {
      if (couponsBuilder_ != null) {
        return couponsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(coupons_);
      }
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public proto.example.Schema.Coupon.Builder addCouponsBuilder() {
      return getCouponsFieldBuilder().addBuilder(
          proto.example.Schema.Coupon.getDefaultInstance());
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public proto.example.Schema.Coupon.Builder addCouponsBuilder(
        int index) {
      return getCouponsFieldBuilder().addBuilder(
          index, proto.example.Schema.Coupon.getDefaultInstance());
    }
    /**
     * <code>repeated .Coupon coupons = 1;</code>
     */
    public java.util.List<proto.example.Schema.Coupon.Builder> 
         getCouponsBuilderList() {
      return getCouponsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.example.Schema.Coupon, proto.example.Schema.Coupon.Builder, proto.example.Schema.CouponOrBuilder> 
        getCouponsFieldBuilder() {
      if (couponsBuilder_ == null) {
        couponsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.example.Schema.Coupon, proto.example.Schema.Coupon.Builder, proto.example.Schema.CouponOrBuilder>(
                coupons_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        coupons_ = null;
      }
      return couponsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Coupons)
  }

  // @@protoc_insertion_point(class_scope:Coupons)
  private static final proto.example.Schema.Coupons DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.example.Schema.Coupons();
  }

  public static proto.example.Schema.Coupons getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Coupons>
      PARSER = new com.google.protobuf.AbstractParser<Coupons>() {
    @java.lang.Override
    public Coupons parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Coupons(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Coupons> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Coupons> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.example.Schema.Coupons getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

