// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface CouponsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Coupons)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  java.util.List<proto.example.Schema.Coupon> 
      getCouponsList();
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  proto.example.Schema.Coupon getCoupons(int index);
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  int getCouponsCount();
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.CouponOrBuilder> 
      getCouponsOrBuilderList();
  /**
   * <code>repeated .Coupon coupons = 1;</code>
   */
  proto.example.Schema.CouponOrBuilder getCouponsOrBuilder(
      int index);
}
