// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface CustomersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Customers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Customer customers = 1;</code>
   */
  java.util.List<proto.example.Schema.Customer> 
      getCustomersList();
  /**
   * <code>repeated .Customer customers = 1;</code>
   */
  proto.example.Schema.Customer getCustomers(int index);
  /**
   * <code>repeated .Customer customers = 1;</code>
   */
  int getCustomersCount();
  /**
   * <code>repeated .Customer customers = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.CustomerOrBuilder> 
      getCustomersOrBuilderList();
  /**
   * <code>repeated .Customer customers = 1;</code>
   */
  proto.example.Schema.CustomerOrBuilder getCustomersOrBuilder(
      int index);
}
