// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

/**
 * Protobuf type {@code IdTrackers}
 */
public final class IdTrackers extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:IdTrackers)
    IdTrackersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IdTrackers.newBuilder() to construct.
  private IdTrackers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IdTrackers() {
    idTrackers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IdTrackers();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IdTrackers(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              idTrackers_ = new java.util.ArrayList<proto.example.Schema.IdTracker>();
              mutable_bitField0_ |= 0x00000001;
            }
            idTrackers_.add(
                input.readMessage(proto.example.Schema.IdTracker.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        idTrackers_ = java.util.Collections.unmodifiableList(idTrackers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.example.Schema.SchemaProtos.internal_static_IdTrackers_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.example.Schema.SchemaProtos.internal_static_IdTrackers_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.example.Schema.IdTrackers.class, proto.example.Schema.IdTrackers.Builder.class);
  }

  public static final int IDTRACKERS_FIELD_NUMBER = 1;
  private java.util.List<proto.example.Schema.IdTracker> idTrackers_;
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<proto.example.Schema.IdTracker> getIdTrackersList() {
    return idTrackers_;
  }
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends proto.example.Schema.IdTrackerOrBuilder> 
      getIdTrackersOrBuilderList() {
    return idTrackers_;
  }
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  @java.lang.Override
  public int getIdTrackersCount() {
    return idTrackers_.size();
  }
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  @java.lang.Override
  public proto.example.Schema.IdTracker getIdTrackers(int index) {
    return idTrackers_.get(index);
  }
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  @java.lang.Override
  public proto.example.Schema.IdTrackerOrBuilder getIdTrackersOrBuilder(
      int index) {
    return idTrackers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < idTrackers_.size(); i++) {
      output.writeMessage(1, idTrackers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < idTrackers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, idTrackers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.example.Schema.IdTrackers)) {
      return super.equals(obj);
    }
    proto.example.Schema.IdTrackers other = (proto.example.Schema.IdTrackers) obj;

    if (!getIdTrackersList()
        .equals(other.getIdTrackersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIdTrackersCount() > 0) {
      hash = (37 * hash) + IDTRACKERS_FIELD_NUMBER;
      hash = (53 * hash) + getIdTrackersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.example.Schema.IdTrackers parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.Schema.IdTrackers parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.example.Schema.IdTrackers parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.example.Schema.IdTrackers parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.example.Schema.IdTrackers parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.example.Schema.IdTrackers parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.example.Schema.IdTrackers prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IdTrackers}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IdTrackers)
      proto.example.Schema.IdTrackersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.example.Schema.SchemaProtos.internal_static_IdTrackers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.example.Schema.SchemaProtos.internal_static_IdTrackers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.example.Schema.IdTrackers.class, proto.example.Schema.IdTrackers.Builder.class);
    }

    // Construct using proto.example.Schema.IdTrackers.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getIdTrackersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idTrackersBuilder_ == null) {
        idTrackers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        idTrackersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.example.Schema.SchemaProtos.internal_static_IdTrackers_descriptor;
    }

    @java.lang.Override
    public proto.example.Schema.IdTrackers getDefaultInstanceForType() {
      return proto.example.Schema.IdTrackers.getDefaultInstance();
    }

    @java.lang.Override
    public proto.example.Schema.IdTrackers build() {
      proto.example.Schema.IdTrackers result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.example.Schema.IdTrackers buildPartial() {
      proto.example.Schema.IdTrackers result = new proto.example.Schema.IdTrackers(this);
      int from_bitField0_ = bitField0_;
      if (idTrackersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          idTrackers_ = java.util.Collections.unmodifiableList(idTrackers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.idTrackers_ = idTrackers_;
      } else {
        result.idTrackers_ = idTrackersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.example.Schema.IdTrackers) {
        return mergeFrom((proto.example.Schema.IdTrackers)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.example.Schema.IdTrackers other) {
      if (other == proto.example.Schema.IdTrackers.getDefaultInstance()) return this;
      if (idTrackersBuilder_ == null) {
        if (!other.idTrackers_.isEmpty()) {
          if (idTrackers_.isEmpty()) {
            idTrackers_ = other.idTrackers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdTrackersIsMutable();
            idTrackers_.addAll(other.idTrackers_);
          }
          onChanged();
        }
      } else {
        if (!other.idTrackers_.isEmpty()) {
          if (idTrackersBuilder_.isEmpty()) {
            idTrackersBuilder_.dispose();
            idTrackersBuilder_ = null;
            idTrackers_ = other.idTrackers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            idTrackersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIdTrackersFieldBuilder() : null;
          } else {
            idTrackersBuilder_.addAllMessages(other.idTrackers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.example.Schema.IdTrackers parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.example.Schema.IdTrackers) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<proto.example.Schema.IdTracker> idTrackers_ =
      java.util.Collections.emptyList();
    private void ensureIdTrackersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        idTrackers_ = new java.util.ArrayList<proto.example.Schema.IdTracker>(idTrackers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.example.Schema.IdTracker, proto.example.Schema.IdTracker.Builder, proto.example.Schema.IdTrackerOrBuilder> idTrackersBuilder_;

    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public java.util.List<proto.example.Schema.IdTracker> getIdTrackersList() {
      if (idTrackersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(idTrackers_);
      } else {
        return idTrackersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public int getIdTrackersCount() {
      if (idTrackersBuilder_ == null) {
        return idTrackers_.size();
      } else {
        return idTrackersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public proto.example.Schema.IdTracker getIdTrackers(int index) {
      if (idTrackersBuilder_ == null) {
        return idTrackers_.get(index);
      } else {
        return idTrackersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder setIdTrackers(
        int index, proto.example.Schema.IdTracker value) {
      if (idTrackersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdTrackersIsMutable();
        idTrackers_.set(index, value);
        onChanged();
      } else {
        idTrackersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder setIdTrackers(
        int index, proto.example.Schema.IdTracker.Builder builderForValue) {
      if (idTrackersBuilder_ == null) {
        ensureIdTrackersIsMutable();
        idTrackers_.set(index, builderForValue.build());
        onChanged();
      } else {
        idTrackersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder addIdTrackers(proto.example.Schema.IdTracker value) {
      if (idTrackersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdTrackersIsMutable();
        idTrackers_.add(value);
        onChanged();
      } else {
        idTrackersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder addIdTrackers(
        int index, proto.example.Schema.IdTracker value) {
      if (idTrackersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIdTrackersIsMutable();
        idTrackers_.add(index, value);
        onChanged();
      } else {
        idTrackersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder addIdTrackers(
        proto.example.Schema.IdTracker.Builder builderForValue) {
      if (idTrackersBuilder_ == null) {
        ensureIdTrackersIsMutable();
        idTrackers_.add(builderForValue.build());
        onChanged();
      } else {
        idTrackersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder addIdTrackers(
        int index, proto.example.Schema.IdTracker.Builder builderForValue) {
      if (idTrackersBuilder_ == null) {
        ensureIdTrackersIsMutable();
        idTrackers_.add(index, builderForValue.build());
        onChanged();
      } else {
        idTrackersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder addAllIdTrackers(
        java.lang.Iterable<? extends proto.example.Schema.IdTracker> values) {
      if (idTrackersBuilder_ == null) {
        ensureIdTrackersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, idTrackers_);
        onChanged();
      } else {
        idTrackersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder clearIdTrackers() {
      if (idTrackersBuilder_ == null) {
        idTrackers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        idTrackersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public Builder removeIdTrackers(int index) {
      if (idTrackersBuilder_ == null) {
        ensureIdTrackersIsMutable();
        idTrackers_.remove(index);
        onChanged();
      } else {
        idTrackersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public proto.example.Schema.IdTracker.Builder getIdTrackersBuilder(
        int index) {
      return getIdTrackersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public proto.example.Schema.IdTrackerOrBuilder getIdTrackersOrBuilder(
        int index) {
      if (idTrackersBuilder_ == null) {
        return idTrackers_.get(index);  } else {
        return idTrackersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public java.util.List<? extends proto.example.Schema.IdTrackerOrBuilder> 
         getIdTrackersOrBuilderList() {
      if (idTrackersBuilder_ != null) {
        return idTrackersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(idTrackers_);
      }
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public proto.example.Schema.IdTracker.Builder addIdTrackersBuilder() {
      return getIdTrackersFieldBuilder().addBuilder(
          proto.example.Schema.IdTracker.getDefaultInstance());
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public proto.example.Schema.IdTracker.Builder addIdTrackersBuilder(
        int index) {
      return getIdTrackersFieldBuilder().addBuilder(
          index, proto.example.Schema.IdTracker.getDefaultInstance());
    }
    /**
     * <code>repeated .IdTracker idTrackers = 1;</code>
     */
    public java.util.List<proto.example.Schema.IdTracker.Builder> 
         getIdTrackersBuilderList() {
      return getIdTrackersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.example.Schema.IdTracker, proto.example.Schema.IdTracker.Builder, proto.example.Schema.IdTrackerOrBuilder> 
        getIdTrackersFieldBuilder() {
      if (idTrackersBuilder_ == null) {
        idTrackersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.example.Schema.IdTracker, proto.example.Schema.IdTracker.Builder, proto.example.Schema.IdTrackerOrBuilder>(
                idTrackers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        idTrackers_ = null;
      }
      return idTrackersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:IdTrackers)
  }

  // @@protoc_insertion_point(class_scope:IdTrackers)
  private static final proto.example.Schema.IdTrackers DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.example.Schema.IdTrackers();
  }

  public static proto.example.Schema.IdTrackers getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IdTrackers>
      PARSER = new com.google.protobuf.AbstractParser<IdTrackers>() {
    @java.lang.Override
    public IdTrackers parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IdTrackers(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IdTrackers> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IdTrackers> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.example.Schema.IdTrackers getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

