// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface IdTrackersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IdTrackers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  java.util.List<proto.example.Schema.IdTracker> 
      getIdTrackersList();
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  proto.example.Schema.IdTracker getIdTrackers(int index);
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  int getIdTrackersCount();
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.IdTrackerOrBuilder> 
      getIdTrackersOrBuilderList();
  /**
   * <code>repeated .IdTracker idTrackers = 1;</code>
   */
  proto.example.Schema.IdTrackerOrBuilder getIdTrackersOrBuilder(
      int index);
}
