// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface OrderProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderId = 1;</code>
   * @return The orderId.
   */
  int getOrderId();

  /**
   * <code>int32 productId = 2;</code>
   * @return The productId.
   */
  int getProductId();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();
}
