// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface OrderProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderProducts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .OrderProduct orderProducts = 1;</code>
   */
  java.util.List<proto.example.Schema.OrderProduct> 
      getOrderProductsList();
  /**
   * <code>repeated .OrderProduct orderProducts = 1;</code>
   */
  proto.example.Schema.OrderProduct getOrderProducts(int index);
  /**
   * <code>repeated .OrderProduct orderProducts = 1;</code>
   */
  int getOrderProductsCount();
  /**
   * <code>repeated .OrderProduct orderProducts = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.OrderProductOrBuilder> 
      getOrderProductsOrBuilderList();
  /**
   * <code>repeated .OrderProduct orderProducts = 1;</code>
   */
  proto.example.Schema.OrderProductOrBuilder getOrderProductsOrBuilder(
      int index);
}
