// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>int32 discount = 3;</code>
   * @return The discount.
   */
  int getDiscount();

  /**
   * <code>double totalAmount = 4;</code>
   * @return The totalAmount.
   */
  double getTotalAmount();

  /**
   * <code>string Time = 5;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string Time = 5;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string Date = 6;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string Date = 6;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
