// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface OrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Orders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Order orders = 1;</code>
   */
  java.util.List<proto.example.Schema.Order> 
      getOrdersList();
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  proto.example.Schema.Order getOrders(int index);
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  int getOrdersCount();
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.OrderOrBuilder> 
      getOrdersOrBuilderList();
  /**
   * <code>repeated .Order orders = 1;</code>
   */
  proto.example.Schema.OrderOrBuilder getOrdersOrBuilder(
      int index);
}
