// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public interface ProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Products)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Product products = 1;</code>
   */
  java.util.List<proto.example.Schema.Product> 
      getProductsList();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  proto.example.Schema.Product getProducts(int index);
  /**
   * <code>repeated .Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  java.util.List<? extends proto.example.Schema.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  proto.example.Schema.ProductOrBuilder getProductsOrBuilder(
      int index);
}
