// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Schema.proto

package proto.example.Schema;

public final class SchemaProtos {
  private SchemaProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IdTracker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IdTracker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IdTrackers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IdTrackers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Customer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Customers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Customers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Products_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Products_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CartItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CartItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Cart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Cart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Orders_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Orders_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderProducts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderProducts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Coupon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Coupon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Coupons_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Coupons_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Schema.proto\")\n\tIdTracker\022\014\n\004name\030\001 \001(" +
      "\t\022\016\n\006lastId\030\002 \001(\005\",\n\nIdTrackers\022\036\n\nidTra" +
      "ckers\030\001 \003(\0132\n.IdTracker\"q\n\010Customer\022\r\n\005e" +
      "mail\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\014\n\004name\030\003 \001" +
      "(\t\022\024\n\014mobileNumber\030\004 \001(\003\022 \n\030isInitialCou" +
      "ponGenerated\030\005 \001(\005\")\n\tCustomers\022\034\n\tcusto" +
      "mers\030\001 \003(\0132\t.Customer\"c\n\007Product\022\n\n\002id\030\001" +
      " \001(\005\022\r\n\005brand\030\002 \001(\t\022\020\n\010category\030\003 \001(\t\022\r\n" +
      "\005model\030\004 \001(\t\022\r\n\005price\030\005 \001(\001\022\r\n\005stock\030\006 \001" +
      "(\005\"&\n\010Products\022\032\n\010products\030\001 \003(\0132\010.Produ" +
      "ct\"W\n\010CartItem\022\r\n\005email\030\001 \001(\t\022\021\n\tproduct" +
      "Id\030\002 \001(\005\022\r\n\005price\030\003 \001(\001\022\014\n\004Time\030\004 \001(\t\022\014\n" +
      "\004Date\030\005 \001(\t\"$\n\004Cart\022\034\n\tcartItems\030\001 \003(\0132\t" +
      ".CartItem\"e\n\005Order\022\n\n\002id\030\001 \001(\005\022\r\n\005email\030" +
      "\002 \001(\t\022\020\n\010discount\030\003 \001(\005\022\023\n\013totalAmount\030\004" +
      " \001(\001\022\014\n\004Time\030\005 \001(\t\022\014\n\004Date\030\006 \001(\t\" \n\006Orde" +
      "rs\022\026\n\006orders\030\001 \003(\0132\006.Order\"A\n\014OrderProdu" +
      "ct\022\017\n\007orderId\030\001 \001(\005\022\021\n\tproductId\030\002 \001(\005\022\r" +
      "\n\005price\030\003 \001(\001\"5\n\rOrderProducts\022$\n\rorderP" +
      "roducts\030\001 \003(\0132\r.OrderProduct\"i\n\006Coupon\022\n" +
      "\n\002id\030\001 \001(\005\022\r\n\005email\030\002 \001(\t\022\024\n\014getOnOrderI" +
      "d\030\003 \001(\005\022\022\n\ncouponCode\030\004 \001(\003\022\014\n\004Time\030\005 \001(" +
      "\t\022\014\n\004Date\030\006 \001(\t\"#\n\007Coupons\022\030\n\007coupons\030\001 " +
      "\003(\0132\007.CouponB&\n\024proto.example.SchemaB\014Sc" +
      "hemaProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IdTracker_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IdTracker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IdTracker_descriptor,
        new java.lang.String[] { "Name", "LastId", });
    internal_static_IdTrackers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IdTrackers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IdTrackers_descriptor,
        new java.lang.String[] { "IdTrackers", });
    internal_static_Customer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Customer_descriptor,
        new java.lang.String[] { "Email", "Password", "Name", "MobileNumber", "IsInitialCouponGenerated", });
    internal_static_Customers_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Customers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Customers_descriptor,
        new java.lang.String[] { "Customers", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Id", "Brand", "Category", "Model", "Price", "Stock", });
    internal_static_Products_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Products_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Products_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_CartItem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CartItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CartItem_descriptor,
        new java.lang.String[] { "Email", "ProductId", "Price", "Time", "Date", });
    internal_static_Cart_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_Cart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Cart_descriptor,
        new java.lang.String[] { "CartItems", });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Id", "Email", "Discount", "TotalAmount", "Time", "Date", });
    internal_static_Orders_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Orders_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Orders_descriptor,
        new java.lang.String[] { "Orders", });
    internal_static_OrderProduct_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_OrderProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderProduct_descriptor,
        new java.lang.String[] { "OrderId", "ProductId", "Price", });
    internal_static_OrderProducts_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_OrderProducts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderProducts_descriptor,
        new java.lang.String[] { "OrderProducts", });
    internal_static_Coupon_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Coupon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Coupon_descriptor,
        new java.lang.String[] { "Id", "Email", "GetOnOrderId", "CouponCode", "Time", "Date", });
    internal_static_Coupons_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_Coupons_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Coupons_descriptor,
        new java.lang.String[] { "Coupons", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
